### ISSUE TITLE
Your mod cannot be built

### ISSUE THREAD

**Issue by Omgise** [Veritaris/Neat#1]
IDEA tells me that `CustomNPC-Plus-1.6-beta2.deobf.jar` is missing
could you please upload this missing file to the repository? Thank you!

**Comment by Veritaris** [comment]
Hi @Omgise! 
Honestly, I think I'm not eligible to share decompiled code of original Custom NPC; but mostly I targeted fork for MC 1.7.10 named [Custom NPC Plus](https://github.com/KAMKEEL/CustomNPC-Plus), so you can easily replace required dependency with KAMKEEL's one from released, there're dev dependencies / separated api repo

**Comment by Omgise** [comment]
Ok, thanks for your help :)
